ThuchanhWeb_Sql/Models/Course.cs
using ThuchanhWeb_Sql.Models;
using System.ComponentModel.DataAnnotations.Schema;

namespace ThuchanhWeb_Sql.Models
{
	public class Course
	{
		[DatabaseGenerated(DatabaseGeneratedOption.None)]
		public int CourseID { get; set; }
		public string Title { get; set; }
		public int Credits { get; set; }
		public ICollection<Enrollment> Enrollments { get; set; }
	}
}

ThuchanhWeb_Sql/Models/Enrollment.cs
namespace ThuchanhWeb_Sql.Models
{
	public class Enrollment
	{
		public int EnrollmentID { get; set; }
		public int CourseID { get; set; }
		public int LearnerID { get; set; }
		public float Grade { get; set; }
		public Learner Learner { get; set; }
		public Course Course { get; set; }
	}
}

ThuchanhWeb_Sql/Models/ErrorViewModel.cs
namespace ThuchanhWeb_Sql.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ThuchanhWeb_Sql/Models/Learner.cs
namespace ThuchanhWeb_Sql.Models
{
	public class Learner
	{
		public int LearnerID { get; set; }
		public string LastName { get; set; }
		public string FirstMidName { get; set; }
		public DateTime EnrollmentDate { get; set; }
		public int MajorID { get; set; }
		public Major Major { get; set; }
		public ICollection<Enrollment> Enrollments { get; set; }
	}
}

ThuchanhWeb_Sql/Models/Major.cs
namespace ThuchanhWeb_Sql.Models
{
	public class Major 
	{
		public int MajorID { get; set; }
		public string MajorName { get; set; }
		public ICollection<Learner> Learners { get; set; }
	}
}

ThuchanhWeb_Sql/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ThuchanhWeb_Sql.Models;

namespace ThuchanhWeb_Sql.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

ThuchanhWeb_Sql/Controllers/LearnerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThuchanhWeb_Sql.Data;
using ThuchanhWeb_Sql.Models;

namespace ThuchanhWeb_Sql.Controllers
{
    public class LearnerController : Controller
    {
        private SchoolContext db;
        public LearnerController(SchoolContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            var learners = db.Learners.Include(m => m.Major).ToList();
            return View(learners);
        }
        //thêm 2 action create
        public IActionResult Create()
        {
            //dùng 1 trong 2 cách để tạo SelectList gửi về View qua ViewBag để
            //hiển thị danh sách chuyên ngành (Majors)
            var majors = new List<SelectListItem>(); //cách 1
            foreach (var item in db.Majors)
            {
                majors.Add(new SelectListItem
                {
                    Text = item.MajorName,

                    Value = item.MajorID.ToString()
                });

            }
            ViewBag.MajorID = majors;
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName"); //cách 2
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("FirstMidName,LastName,MajorID,EnrollmentDate")] Learner learner)
        {
            if (ModelState.IsValid)
            {
                db.Learners.Add(learner);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            //lại dùng 1 trong 2 cách tạo SelectList gửi về View để hiển thị danh sách Majors
            ViewBag.MajorID = new SelectList(db.Majors, "MajorID", "MajorName");
            return View();

        }
    }
}

ThuchanhWeb_Sql/Views/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
ViewData["Title"] = "Create";
Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@model Learner
<h1>Create</h1>
<div>
<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="Learner" asp-action="Create" method="post" class="mt-3">
<div style="margin-top:7px" class="form-group row">
<label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name">
</div>
<span asp-validation-for="FirstMidName" class="text-danger"></span>
</div>
<div style="margin-top:7px" class="form-group row">
<label asp-for="LastName" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<input asp-for="LastName" class="form-control" placeholder="Last Name">
</div>
<span asp-validation-for="LastName" class="text-danger"></span>
</div>
<div style="margin-top:7px" class="form-group row">
<label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<select asp-for="MajorID" class="custom-select mr-sm-2"
asp-items="@ViewBag.MajorID"></select>
</div>
<span asp-validation-for="MajorID" class="text-danger"></span>
</div>
<div style="margin-top:7px" class="form-group row">
<label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<input asp-for="EnrollmentDate" class="form-control">
</div>
<span asp-validation-for="EnrollmentDate" class="text-danger"></span>
</div>
<div style="margin-top:10px" class="form-group row">
<div class="col-sm-10">
<button type="submit" class="btn btn-primary">Create</button>
</div>
</div>
</form>
</div>

ThuchanhWeb_Sql/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ThuchanhWeb_Sql/Views/Learner/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
ViewData["Title"] = "Create";
Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@model Learner
<h1>Create</h1>
<div>
<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="Learner" asp-action="Create" method="post" class="mt-3">
<div style="margin-top:7px" class="form-group row">
<label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name">
</div>
<span asp-validation-for="FirstMidName" class="text-danger"></span>
</div>
<div style="margin-top:7px" class="form-group row">
<label asp-for="LastName" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<input asp-for="LastName" class="form-control" placeholder="Last Name">
</div>
<span asp-validation-for="LastName" class="text-danger"></span>
</div>
<div style="margin-top:7px" class="form-group row">
<label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<select asp-for="MajorID" class="custom-select mr-sm-2"
asp-items="@ViewBag.MajorID"></select>
</div>
<span asp-validation-for="MajorID" class="text-danger"></span>
</div>
<div style="margin-top:7px" class="form-group row">
<label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<input asp-for="EnrollmentDate" class="form-control">
</div>
<span asp-validation-for="EnrollmentDate" class="text-danger"></span>
</div>
<div style="margin-top:10px" class="form-group row">
<div class="col-sm-10">
<button type="submit" class="btn btn-primary">Create</button>
</div>
</div>
</form>
</div>

ThuchanhWeb_Sql/Views/Learner/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MyLayout.cshtml";

}
@model IEnumerable<Learner>
<h1>Learner List</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Mã</th>
            <th>Tên</th>
            <th>Họ</th>
            <th>Ngành</th>
            <th>Ngày Nhập Học</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>@s.LearnerID</td>
                <td>@s.FirstMidName</td>
                <td>@s.LastName</td>
                <td>@s.Major.MajorName</td>
                <td>@s.EnrollmentDate</td>
                <td><a asp-action="Edit">Edit</a>|<a asp-action="Delete">Delete</a></td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Create" class="btn btn-primary">Create New Student</a>

ThuchanhWeb_Sql/Views/Shared/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
ViewData["Title"] = "Create";
Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@model Learner
<h1>Create</h1>
<div>
<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="Learner" asp-action="Create" method="post" class="mt-3">
<div style="margin-top:7px" class="form-group row">
<label asp-for="FirstMidName" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<input asp-for="FirstMidName" class="form-control" placeholder="First Mid Name">
</div>
<span asp-validation-for="FirstMidName" class="text-danger"></span>
</div>
<div style="margin-top:7px" class="form-group row">
<label asp-for="LastName" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<input asp-for="LastName" class="form-control" placeholder="Last Name">
</div>
<span asp-validation-for="LastName" class="text-danger"></span>
</div>
<div style="margin-top:7px" class="form-group row">
<label asp-for="MajorID" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<select asp-for="MajorID" class="custom-select mr-sm-2"
asp-items="@ViewBag.MajorID"></select>
</div>
<span asp-validation-for="MajorID" class="text-danger"></span>
</div>
<div style="margin-top:7px" class="form-group row">
<label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
<div class="col-sm-10">
<input asp-for="EnrollmentDate" class="form-control">
</div>
<span asp-validation-for="EnrollmentDate" class="text-danger"></span>
</div>
<div style="margin-top:10px" class="form-group row">
<div class="col-sm-10">
<button type="submit" class="btn btn-primary">Create</button>
</div>
</div>
</form>
</div>

ThuchanhWeb_Sql/Views/Shared/Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; 2023</div>
        </div>
    </div>

ThuchanhWeb_Sql/Views/Shared/LeftMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="index.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">Addons</div>
                <a class="nav-link" href="charts.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Branches
                </a>
                <a class="nav-link" href="tables.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                    Students
                </a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as: MyAccount</div>
        </div>
    </nav>
</div>

ThuchanhWeb_Sql/Views/Shared/TopNav.cshtml
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="">Management System</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">Settings</a></li>
                <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="#!">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>

ThuchanhWeb_Sql/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThuchanhWeb_Sql</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ThuchanhWeb_Sql.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ThuchanhWeb_Sql</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ThuchanhWeb_Sql - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ThuchanhWeb_Sql/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] -  Management System</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <!-- Begin Top nav -->
    <partial name="TopNav" />
    <!-- End Top nav -->
    <div id="layoutSidenav">
        <!-- Begin Left menu -->
        <partial name="LeftMenu" />
        <!-- End Left menu -->
        <!-- Begin Right content -->
        <div id="layoutSidenav_content">
            <!-- Begin Main -->
            <main>
                @RenderBody()
            </main>
            <!-- End Main -->
            <!-- Begin Footer -->
            <footer class="py-4 bg-light mt-auto">
                <partial name="Footer" />
                <!-- End Footer -->
            </footer>
        </div>
        <!-- End Right content -->
    </div>
    <script src="~/js/scripts.js"></script>
    @await RenderSectionAsync("Scripts",required : false);
</body>
</html>